<?xml version="1.0"?>
<package format="3">
  <name>gen_local_goal</name>
  <version>0.0.0</version>
  <description>The gen_local_goal package</description>

  <maintainer email="2120230386@mail.nankai.edu.cn">Qingchen Bi</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
  
</package>
